### ISSUE TITLE
还有这好东西

### ISSUE THREAD

**Issue by Soirks** [DoomsdayTechStudio/SeewoFU#1]
感谢大佬！！
请问有办法破解冰点还原吗

**Comment by xiewoc** [comment]
6,还以为出Bug了

**Comment by xiewoc** [comment]
那个冰点还原的话看https://www.bilibili.com/video/BV1fu4y1R7p4/ up是[--昵称长度太短了](https://space.bilibili.com/445328483)

**Comment by xiewoc** [comment]
> 感谢大佬！！ 请问有办法破解冰点还原吗
那个冰点还原的话看https://www.bilibili.com/video/BV1fu4y1R7p4/ up是[--昵称长度太短了](https://space.bilibili.com/445328483)
